name: CI

on: [push]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.212'
    - name: Setup Env
      run: ./scripts/setup.sh ${{ matrix.os }}
    - name: Build Jar
      run: ./scripts/compile-maven.sh
    - name: Compile Binary
      run: ./scripts/build.sh ${{ matrix.os }}
    - name: Upload ${{ matrix.os }} Binary
      if: matrix.os == 'macOS-10.14'
      uses: actions/upload-artifact@master
      with:
        name: titan-cli-0.3.0-darwin_amd64.zip
        path: releases/0.3.0
    - name: Upload ${{ matrix.os }} Binary
      if: matrix.os == 'ubuntu-18.04'
      uses: actions/upload-artifact@master
      with:
        name: titan-cli-0.3.0-linux_amd64.zip
        path:releases/0.3.0
  check:
    name: Check Releases
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: titan-cli-0.3.0-darwin_amd64.zip
          path: releases/0.3.0
      - uses: actions/download-artifact@master
        with:
          name: titan-cli-0.3.0-linux_amd64.zip
          path: releases/0.3.0
      - run: cat ${PWD}/releases/0.3.0

#  built-osx:
#    name: build osx
#    runs-on: macOS-10.14
#    steps:
#    - uses: actions/checkout@v1
#    - name: Install Graal VM
#      run: |
#        curl -L https://github.com/oracle/graal/releases/download/vm-19.0.0/graalvm-ce-darwin-amd64-19.0.0.tar.gz --output graal.tar.gz
#        gunzip -c graal.tar.gz | tar xopf -
#        export PATH=${PWD}/graalvm-ce-19.0.0/Contents/Home/bin:$PATH
#        export JAVA_HOME=${PWD}/graalvm-ce-19.0.0/Contents/Home/jre
#        gu install native-image
#    - name: Build Jar
#      run: ./scripts/compile-maven.sh
#    - name: Compile Binary
#      run: |
#        export PATH=${PWD}/graalvm-ce-19.0.0/Contents/Home/bin:$PATH
#        export JAVA_HOME=${PWD}/graalvm-ce-19.0.0/Contents/Home/jre
#        /bin/bash ${PWD}/scripts/build-osx.sh

#  build-windows:
#    name: build windows
#    runs-on: windows-2019
#    steps:
#    - uses: actions/checkout@v1
#    - name: Install Graal VM
#      run: | 
#        choco install graalvm --version 19.1.0 maven --version 3.6.1
#        SET JAVA_HOME=C:\Program Files\GraalVM\graalvm-ce-19.1.0\jre
#        SET GRAAL_BIN=C:\Program Files\GraalVM\graalvm-ce-19.1.0\bin
#        SET PATH=%GRAAL_BIN%;%PATH%
#    - name: Install Native Image
#      run: gu install native-image
#    - name: Build Jar
#      run: mvn clean package
      
